# Generated by Django 5.2.5 on 2025-11-07 06:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('investment_type', models.CharField(choices=[('Stock', 'Stock'), ('Mutual Fund', 'Mutual Fund'), ('FD', 'Fixed Deposit'), ('RD', 'Recurring Deposit'), ('Bond', 'Bond'), ('ETF', 'Exchange-Traded Fund'), ('Pension', 'Pension Fund'), ('Gold', 'Gold'), ('Crypto', 'Cryptocurrency'), ('Real Estate', 'Real Estate'), ('Other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_return', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Biannual', 'Biannual'), ('Yearly', 'Yearly')], default='Yearly', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
