# Generated by Django 5.2.5 on 2025-11-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='expected_return',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
