# Generated by Django 5.2.5 on 2025-11-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Biannual', 'Biannual'), ('Yearly', 'Yearly')], default='Yearly', max_length=20),
        ),
    ]
