# Generated by Django 5.2.5 on 2025-11-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_investment_expected_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='expected_return',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
