# Generated by Django 5.2.5 on 2025-11-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_alter_investment_expected_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
