# Generated by Django 5.2.5 on 2025-11-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_investment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='notes',
        ),
        migrations.AddField(
            model_name='investment',
            name='frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Biannual', 'Biannual'), ('Yearly', 'Yearly')], default='Yearly', max_length=20),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investment_type',
            field=models.CharField(choices=[('Stock', 'Stock'), ('Mutual Fund', 'Mutual Fund'), ('FD', 'Fixed Deposit'), ('RD', 'Recurring Deposit'), ('Bond', 'Bond'), ('ETF', 'Exchange-Traded Fund'), ('Pension', 'Pension Fund'), ('Gold', 'Gold'), ('Crypto', 'Cryptocurrency'), ('Real Estate', 'Real Estate'), ('Other', 'Other')], max_length=50),
        ),
    ]
