# Generated by Django 5.2.5 on 2025-10-20 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=21)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannually', 'Biannually'), ('yearly', 'Yearly')], max_length=20)),
                ('category', models.CharField(choices=[('Housing & Utilities', 'Housing & Utilities'), ('Transportation', 'Transportation'), ('Food & Dining', 'Food & Dining'), ('Health & Fitness', 'Health & Fitness'), ('Entertainment & Leisure', 'Entertainment & Leisure'), ('Education', 'Education'), ('Financial', 'Financial'), ('Miscellaneous', 'Miscellaneous')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=21)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Housing & Utilities', 'Housing & Utilities'), ('Transportation', 'Transportation'), ('Food & Dining', 'Food & Dining'), ('Personal & Shopping', 'Personal & Shopping'), ('Health & Fitness', 'Health & Fitness'), ('Entertainment & Leisure', 'Entertainment & Leisure'), ('Education', 'Education'), ('Financial', 'Financial'), ('Travel & Vacation', 'Travel & Vacation'), ('Miscellaneous', 'Miscellaneous')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recurring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.recurringexpense')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=21)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannually', 'Biannually'), ('yearly', 'Yearly')], max_length=20)),
                ('category', models.CharField(choices=[('Salary', 'Salary'), ('Business', 'Business'), ('Freelance', 'Freelance'), ('Rental Income', 'Rental Income'), ('Dividends', 'Dividends'), ('Interest Income', 'Interest Income'), ('Retirement Income', 'Retirement Income'), ('Other Income', 'Other Income')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=21)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Salary', 'Salary'), ('Business', 'Business'), ('Freelance', 'Freelance'), ('Rental Income', 'Rental Income'), ('Dividends', 'Dividends'), ('Interest Income', 'Interest Income'), ('Gifts & Donations', 'Gifts & Donations'), ('Refunds', 'Refunds'), ('Retirement Income', 'Retirement Income'), ('Bonus & Incentives', 'Bonus & Incentives'), ('Other Income', 'Other Income')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recurring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.recurringincome')),
            ],
        ),
    ]
