# Generated by Django 5.2.5 on 2025-11-07 06:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_percent', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Housing & Utilities', 'Housing & Utilities'), ('Transportation', 'Transportation'), ('Food & Dining', 'Food & Dining'), ('Personal & Shopping', 'Personal & Shopping'), ('Health & Fitness', 'Health & Fitness'), ('Entertainment & Leisure', 'Entertainment & Leisure'), ('Education', 'Education'), ('Financial', 'Financial'), ('Travel & Vacation', 'Travel & Vacation'), ('Miscellaneous', 'Miscellaneous')], max_length=50)),
                ('percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='budget.budget')),
            ],
        ),
    ]
