# Generated by Django 5.2.5 on 2025-10-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcategory',
            name='category',
            field=models.CharField(choices=[('Auto-predict', 'Auto-predict'), ('Housing & Utilities', 'Housing & Utilities'), ('Transportation', 'Transportation'), ('Food & Dining', 'Food & Dining'), ('Personal & Shopping', 'Personal & Shopping'), ('Health & Fitness', 'Health & Fitness'), ('Entertainment & Leisure', 'Entertainment & Leisure'), ('Education', 'Education'), ('Financial', 'Financial'), ('Travel & Vacation', 'Travel & Vacation'), ('Miscellaneous', 'Miscellaneous')], max_length=50),
        ),
    ]
